language: node_js
sudo: false
node_js:
  - '8.9.1'
addons:
  chrome: stable

script: ./scripts/run-tests.sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true

cache:
  yarn: true
  directories:
    - node_modules
