language: node_js
sudo: required
node_js:
  - '8.9.1'
apt:
	packages:
		- google-chrome-stable

before_script:
  - sh -e /etc/init.d/xvfb start

script: ./scripts/run-tests.sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true

cache:
  yarn: true
  directories:
    - node_modules
