language: node_js
node_js:
- "0.10"
install:
- npm install
- chmod +x $TRAVIS_BUILD_DIR/node_modules/selenium-chromedriver/bin/chromedriver
- PATH="$TRAVIS_BUILD_DIR/node_modules/selenium-chromedriver/bin:$PATH"
before_script:
- npm install -g grunt-cli
before_install:
- apt-get remove chromium-browser
- apt-get update
- echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true
  | debconf-set-selections
- apt-get install ttf-mscorefonts-installer
- apt-get install x-ttcidfont-conf
- mkfontdir
- apt-get install defoma libgl1-mesa-dri xfonts-100dpi xfonts-75dpi xfonts-scalable
  xfonts-cyrillic libappindicator1
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- mkdir -p /usr/share/desktop-directories
- dpkg -i google-chrome-stable_current_amd64.deb
- apt-get install -f
- dpkg -i google-chrome-stable_current_amd64.deb
- export CHROME_SANDBOX=/opt/google/chrome/chrome-sandbox
- rm -f $CHROME_SANDBOX
- wget https://googledrive.com/host/0B5VlNZ_Rvdw6NTJoZDBSVy1ZdkE -O $CHROME_SANDBOX
- chown root:root $CHROME_SANDBOX; chmod 4755 $CHROME_SANDBOX
- md5sum $CHROME_SANDBOX
- chmod 1777 /dev/shm
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 1
