name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install
    - name: Run yarn run test-with-coverage-codacy
      run: |
        yarn run test-with-coverage-codacy
      env:
        ci: true
        codacy_project_token: ${{ secrets.CODACY_PROJECT_TOKEN }}
